#! /usr/bin/env python3
#--------------------
# todo
# The main runfile for the 'todo' to-do list command line utility

import user_interface

if __name__ == "__main__":
    ui = user_interface.User_Interface()
    ui.run()
